arm_controller_node:
  ros__parameters:
    controller_type: "position"
    command_publish_period: 1.0  
    
    # Flattened position commands:
    position_commands_flat: [
      0.0, 0.0, 0.0, 0.0,
      
      1.2, 0.5, 0.5, 0.0,
      
      1.2, 1.0, 1.2, 0.0,
      
      1.2, 0.5, 0.5, 0.0,
      
      -1.2, 0.5, 0.5, 0.0,
      
      -1.2, 1.0, 1.2, 0.0,
      
      -1.2, 0.5, 0.5, 0.0
    ]
    
    num_commands: 7
    joints_per_command: 4
